In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn import datasets

In [3]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_class

In [4]:
data = datasets.load_digits()

In [5]:
x = data.data

In [6]:
y = data.target

In [7]:
from sklearn.decomposition import PCA

In [8]:
pca = PCA(n_components=32)

In [9]:
x_pca = pca.fit_transform(x)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_pca,y,test_size=0.3,random_state=0)

In [11]:
from sklearn.naive_bayes import GaussianNB

In [12]:
gnb = GaussianNB()

In [13]:
gnb.fit(x_train,y_train)

GaussianNB()

In [14]:
y_pred = gnb.predict(x_test)

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.937037037037037

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[43  0  0  0  0  0  0  0  1  1]
 [ 0 50  0  0  0  1  0  0  1  0]
 [ 0  1 50  1  0  0  0  0  1  0]
 [ 0  0  2 47  0  0  0  1  2  2]
 [ 0  0  0  0 46  0  0  2  0  0]
 [ 0  0  0  0  0 51  0  0  0  6]
 [ 0  0  0  0  0  0 58  0  1  1]
 [ 0  0  0  0  0  0  0 52  0  1]
 [ 0  1  0  0  0  0  1  0 55  4]
 [ 0  0  0  0  0  1  0  2  0 54]]


In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98        45
           1       0.96      0.96      0.96        52
           2       0.96      0.94      0.95        53
           3       0.98      0.87      0.92        54
           4       1.00      0.96      0.98        48
           5       0.96      0.89      0.93        57
           6       0.98      0.97      0.97        60
           7       0.91      0.98      0.95        53
           8       0.90      0.90      0.90        61
           9       0.78      0.95      0.86        57

    accuracy                           0.94       540
   macro avg       0.94      0.94      0.94       540
weighted avg       0.94      0.94      0.94       540



In [24]:
from sklearn import datasets
iris = datasets.load_iris()

In [25]:
gnb = GaussianNB()
y_pred = gnb.fit(iris.data, iris.target).predict(iris.data)
# print(confusion_matrix(iris.target, y_pred))
print(classification_report(iris.target, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150



In [26]:
from sklearn.naive_bayes import MultinomialNB


In [27]:
mnb = MultinomialNB()
y_pred = mnb.fit(iris.data, iris.target).predict(iris.data)
# print(confusion_matrix(iris.target, y_pred))
print(classification_report(iris.target, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.92      0.93        50
           2       0.92      0.94      0.93        50

    accuracy                           0.95       150
   macro avg       0.95      0.95      0.95       150
weighted avg       0.95      0.95      0.95       150

