# <center>#5 - II : Logic Gates using ANN</center>

In [1]:
import numpy as np

In [2]:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
target_output = np.array([[1,0,0,0]])
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[1],
       [0],
       [0],
       [0]])

In [4]:
weights = np.array([[0.1],[0.2]])
print(weights.shape)
weights

(2, 1)


array([[0.1],
       [0.2]])

In [5]:
bias = 0.3
lr=0.05

In [8]:
for epoch in range(10000):
    inputs = input_features
    in_dot = np.dot(inputs,weights)+bias
    out = sigmoid(in_dot)
    error = out -target_output
    # print(error.sum())
    derror_dout = error
    dout_din = sigmoid_der(out)
    deriv = derror_dout*dout_din
    inputs = input_features.T
    deriv_final = np.dot(inputs,deriv)
    weights -=lr*deriv_final

    for i in deriv:
        bias -= lr *i


In [9]:
print(weights,bias)

[[-7.04686713]
 [-7.04651572]] [2.93774608]


In [10]:
single_point = np.array([1,0])
result1 = np.dot(single_point, weights) + bias
result2 = sigmoid(result1)
print(result2)
single_point = np.array([1,1])
result1 = np.dot(single_point, weights) + bias
result2 = sigmoid(result1)
print(result2)
single_point = np.array([0,0])
result1 = np.dot(single_point, weights) + bias
result2 = sigmoid(result1)
print(result2)

[0.01615687]
[1.42942806e-05]
[0.94968113]


In [6]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [7]:
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))


In [11]:
def func(input_features,target_output):
    weights = np.array([[0.1],[0.2]])
    bias = 0.3
    lr=0.05
    for epoch in range(10000):
        inputs = input_features
        in_dot = np.dot(inputs,weights)+bias
        out = sigmoid(in_dot)
        error = out -target_output
        # print(error.sum())
        derror_dout = error
        dout_din = sigmoid_der(out)
        deriv = derror_dout*dout_din
        inputs = input_features.T
        deriv_final = np.dot(inputs,deriv)
        weights -=lr*deriv_final

        for i in deriv:
            bias -= lr *i
    single_point = np.array([1,0])
    result1 = np.dot(single_point, weights) + bias
    result2 = sigmoid(result1)
    print(f"[1,0] {result2}")
    single_point = np.array([1,1])
    result1 = np.dot(single_point, weights) + bias
    result2 = sigmoid(result1)
    print(f"[1,1] {result2}")
    single_point = np.array([0,0])
    result1 = np.dot(single_point, weights) + bias
    result2 = sigmoid(result1)
    print(f"[0,0] {result2}")  

# OR

In [12]:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
target_output = np.array([[0,1,1,1]])
target_output = target_output.reshape(4,1)
func(input_features,target_output)

[1,0] [0.9793702]
[1,1] [0.99998097]
[0,0] [0.04112867]


# And

In [13]:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
target_output = np.array([[0,0,0,1]])
target_output = target_output.reshape(4,1)
func(input_features,target_output)

[1,0] [0.03914052]
[1,1] [0.93236812]
[0,0] [0.00012035]


# NOR

In [14]:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
target_output = np.array([[1,0,0,0]])
target_output = target_output.reshape(4,1)
func(input_features,target_output)

[1,0] [0.01615687]
[1,1] [1.42942806e-05]
[0,0] [0.94968113]


# NAND

In [15]:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
target_output = np.array([[1,1,1,0]])
target_output = target_output.reshape(4,1)
func(input_features,target_output)

[1,0] [0.95137821]
[1,1] [0.05486444]
[0,0] [0.9998484]
