In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn as sk

In [2]:
data = pd.read_csv("../data-library/yeast/yeast.data",sep='\s+',names=['Sequence Name','mcg','gvh','alm','mit','erl','pox','vac','nuc','class'])

In [3]:
data.head()

Sequence Name   mcg   gvh   alm   mit  erl  pox   vac   nuc class
0    ADT1_YEAST  0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22   MIT
1    ADT2_YEAST  0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22   MIT
2    ADT3_YEAST  0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22   MIT
3    AAR2_YEAST  0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22   NUC
4    AATM_YEAST  0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22   MIT

In [4]:
x = data.drop(['Sequence Name','class'],axis=1)

In [5]:
y = data['class']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [8]:
from sklearn import svm

In [9]:
classifier = svm.SVC()

In [10]:
classifier.fit(x_train,y_train)

SVC()

In [11]:
y_pred = classifier.predict(x_test)

In [12]:
from sklearn.metrics import accuracy_score
print("accuracy score ",accuracy_score(y_true = y_test,y_pred = y_pred))

accuracy score  0.5983827493261455


In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[90  0  0  0  0  0 11 14  0  0]
 [ 0  1  0  0  0  0  0  0  0  0]
 [ 3  0  5  3  1  0  1  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 2  0  1  2  4  1  2  0  0  0]
 [ 7  0  0  0  0 32  0  4  0  0]
 [20  0  0  1  1  2 32  4  0  0]
 [54  0  0  0  1  2  4 47  0  0]
 [ 2  0  0  0  0  0  1  0  4  0]
 [ 4  0  1  0  0  0  0  0  0  0]]
              precision    recall  f1-score   support

         CYT       0.49      0.78      0.61       115
         ERL       1.00      1.00      1.00         1
         EXC       0.71      0.38      0.50        13
         ME1       0.54      1.00      0.70         7
         ME2       0.57      0.33      0.42        12
         ME3       0.86      0.74      0.80        43
         MIT       0.63      0.53      0.58        60
         NUC       0.68      0.44      0.53       108
         POX       1.00      0.57      0.73         7
         VAC       0.00      0.00      0.00         5

    accuracy                           0.60       371
   macro avg       

/home/ankit/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ankit/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ankit/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
data = pd.read_csv("../data-library/Social_Network_Ads.csv")

In [15]:
gender = {'Male': 1,'Female': 2}  
data.Gender = [gender[item] for item in data.Gender] 

In [16]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       2   26            43000          0
3  15603246       2   27            57000          0
4  15804002       1   19            76000          0

In [17]:
x = data.drop(['User ID','Purchased'],axis=1)

In [18]:
y = data['Purchased']

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [20]:
classifier = svm.SVC()

In [21]:
classifier.fit(x_train,y_train)

SVC()

In [22]:
y_pred = classifier.predict(x_test)

In [23]:
from sklearn.metrics import accuracy_score
print("accuracy score ",accuracy_score(y_true = y_test,y_pred = y_pred))

accuracy score  0.81


In [24]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[70  2]
 [17 11]]
              precision    recall  f1-score   support

           0       0.80      0.97      0.88        72
           1       0.85      0.39      0.54        28

    accuracy                           0.81       100
   macro avg       0.83      0.68      0.71       100
weighted avg       0.82      0.81      0.78       100



In [25]:
def fun(x,y):
    x_train,x_test,y_train,y_test = train_test_split(x,y)
    classifier = svm.SVC()
    classifier.fit(x_train,y_train)
    y_pred = classifier.predict(x_test)
    print("accuracy score ",accuracy_score(y_true = y_test,y_pred = y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
data = pd.read_csv("../data-library/Social_Network_Ads.csv")
gender = {'Male': 0,'Female': 1}  
data.Gender = [gender[item] for item in data.Gender] 

In [28]:
x = data.drop(['User ID','Purchased'],axis=1)
y = data['Purchased']

In [29]:
scaler = MinMaxScaler()
x=scaler.fit_transform(x)

In [30]:
fun(x,y)

accuracy score  0.93
[[57  3]
 [ 4 36]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94        60
           1       0.92      0.90      0.91        40

    accuracy                           0.93       100
   macro avg       0.93      0.93      0.93       100
weighted avg       0.93      0.93      0.93       100



In [31]:
data = pd.read_csv("../data-library/servo.data",names=['motor','screw','pgain','vgain','class'])

In [32]:
data.head()

motor screw  pgain  vgain     class
0     E     E      5      4  0.281251
1     B     D      6      5  0.506252
2     D     D      4      3  0.356251
3     B     A      3      2  5.500033
4     D     B      6      5  0.356251

In [33]:
replace = {'A': 0,'B': 1,'C':2,'D':3,'E':4}  
data.motor = [replace[item] for item in data.motor]
data.screw = [replace[item] for item in data.screw]

In [34]:
x= data.drop('class',axis=1)
y=data['class']

In [35]:
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [37]:
classifier = svm.SVR()

In [38]:
classifier.fit(x_train,y_train)

SVR()

In [39]:
y_pred=classifier.predict(x_test)

In [40]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

0.37597229273476246

In [41]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

0.7189986882745709