![lab2](lab2.png)

dataset downloaded from here -> [Qualitative_Bankruptcy Data Set](https://archive.ics.uci.edu/ml/datasets/Qualitative_Bankruptcy)

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('../data-library/Qualitative_Bankruptcy/Qualitative_Bankruptcy.data.txt',names = ['Industrial Risk','Management Risk','Financial Flexibility','Credibility','Competitiveness','Operating Risk','Class'])

In [4]:
data.sample(10)

Industrial Risk Management Risk Financial Flexibility Credibility  \
225               P               N                     N           N   
93                A               A                     N           P   
147               N               N                     N           N   
8                 P               P                     A           P   
190               N               N                     N           N   
226               N               A                     N           N   
191               P               N                     N           N   
126               N               N                     P           A   
43                A               P                     P           A   
216               P               N                     N           N   

    Competitiveness Operating Risk Class  
225               N              N     B  
93                P              P    NB  
147               N              N     B  
8                 A              P    NB  
190               N              N     B  
226               N              P     B  
191               A              A     B  
126               P              N    NB  
43                P              N    NB  
216               N              N     B

In [5]:
print("shape of data: ",data.shape)

shape of data:  (250, 7)


In [6]:
if data.isnull().sum().sum() ==0 :
    print("no null entries")
else:
    print("data preprocessing required")

no null entries


preparing the data

In [7]:
x = data.drop('Class',axis=1)

In [8]:
y = data['Class']

In [9]:
from sklearn.preprocessing import OrdinalEncoder
enc=OrdinalEncoder()
x[['Industrial Risk','Management Risk','Financial Flexibility','Credibility','Competitiveness','Operating Risk']]=enc.fit_transform(x[['Industrial Risk','Management Risk','Financial Flexibility','Credibility','Competitiveness','Operating Risk']])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)

DecisionTreeClassifier()

In [14]:
y_pred = classifier.predict(x_test)

In [15]:
from sklearn.metrics import accuracy_score
print("accuracy score ",accuracy_score(y_true = y_test,y_pred = y_pred))

accuracy score  1.0


In [16]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[23  0]
 [ 0 52]]
              precision    recall  f1-score   support

           B       1.00      1.00      1.00        23
          NB       1.00      1.00      1.00        52

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75



In [17]:
data

Industrial Risk Management Risk Financial Flexibility Credibility  \
0                 P               P                     A           A   
1                 N               N                     A           A   
2                 A               A                     A           A   
3                 P               P                     P           P   
4                 N               N                     P           P   
..              ...             ...                   ...         ...   
245               N               N                     A           N   
246               P               N                     N           N   
247               A               N                     N           N   
248               N               N                     N           N   
249               P               N                     N           N   

    Competitiveness Operating Risk Class  
0                 A              P    NB  
1                 A              N    NB  
2                 A              A    NB  
3                 P              P    NB  
4                 P              N    NB  
..              ...            ...   ...  
245               N              N     B  
246               N              N     B  
247               N              N     B  
248               N              N     B  
249               A              A     B  

[250 rows x 7 columns]

In [19]:
data = pd.read_csv("../data-library/yeast/yeast.data",sep='\s+',names=['Sequence Name','mcg','gvh','alm','mit','erl','pox','vac','nuc'])

In [20]:
x = data.drop('nuc',axis=1)

In [21]:
y = data['nuc']

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [23]:
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [24]:
y_pred = classifier.predict(x_test)

In [25]:
from sklearn.metrics import accuracy_score
print("accuracy score ",accuracy_score(y_true = y_test,y_pred = y_pred))

accuracy score  0.4798206278026906


In [26]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[71  0  2  1  4  3 15 46  1  2]
 [ 0  0  0  0  1  0  0  0  0  0]
 [ 0  0  6  1  1  0  2  1  1  0]
 [ 0  0  0  7  0  0  1  0  0  0]
 [ 1  1  2  1  3  0  2  5  0  5]
 [ 2  0  0  0  1 31  2  4  0  0]
 [14  0  1  0  1  3 41 19  2  2]
 [48  0  1  0  0  5 11 53  4  2]
 [ 0  0  0  1  0  0  0  0  2  0]
 [ 3  0  0  1  1  2  0  3  0  0]]
              precision    recall  f1-score   support

         CYT       0.51      0.49      0.50       145
         ERL       0.00      0.00      0.00         1
         EXC       0.50      0.50      0.50        12
         ME1       0.58      0.88      0.70         8
         ME2       0.25      0.15      0.19        20
         ME3       0.70      0.78      0.74        40
         MIT       0.55      0.49      0.52        83
         NUC       0.40      0.43      0.42       124
         POX       0.20      0.67      0.31         3
         VAC       0.00      0.00      0.00        10

    accuracy                           0.48       446
   macro avg       

In [27]:
data = pd.read_csv("../data-library/petrol_consumption.csv")

In [28]:
data.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [29]:
data.isnull().sum().sum()

0

In [30]:
data.dtypes

Petrol_tax                      float64
Average_income                    int64
Paved_Highways                    int64
Population_Driver_licence(%)    float64
Petrol_Consumption                int64
dtype: object

In [31]:
x = data.drop('Petrol_Consumption', axis=1)
y = data['Petrol_Consumption']

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [33]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [34]:
y_pred = regressor.predict(x_test)

In [35]:
from sklearn import metrics

Mean Absolute Error

In [36]:
metrics.mean_absolute_error(y_test, y_pred)

54.2

Mean Squared Error

In [37]:
metrics.mean_squared_error(y_test, y_pred)

6217.0